openapi: '3.0.0'
info:
  title: Tidepool API
  termsOfService: https://tidepool.org/terms
  contact:
    name: API Support
    url: https://support.tidepool.org/
    email: support@tidepool.org
  license:
    name: BSD 2-Clause "Simplified" License
    url: https://github.com/tidepool-org/platform/blob/master/LICENSE
  version: v1
servers:
    - url: http://localhost:8009
      description: Local
    - url: https://dev-api.tidepool.org
      description: Development [Internal Use Only]
    - url: https://stg-api.tidepool.org
      description: Staging [Internal Use Only]
    - url: https://int-api.tidepool.org
      description: Integration
    - url: https://api.tidepool.org
      description: Production [Requires Approval]
components:
  parameters:
    userId:
      name: userId
      in: path
      description: The id of a user.
      required: true
      schema:
        $ref: users.yaml#/components/schemas/UserId
  schemas:
    UserId:
      type: string
      description: The id of an user.
      format: userId
      example: a43d25a01f
