# Development
FROM golang:1.12-alpine AS development
WORKDIR /go/src/github.com/tidepool-org/platform
RUN apk --no-cache add git make tzdata && \
    apk add --no-cache ca-certificates tzdata && \
    go get github.com/githubnemo/CompileDaemon && \
    adduser -D tidepool && \
    chown -R tidepool /go/src/github.com/tidepool-org/platform
USER tidepool
COPY . .
ENV SERVICE=services/data
RUN ["make", "service-build"]
CMD ["make", "service-start"]

# Production
FROM alpine:latest AS production
RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk add --no-cache ca-certificates tzdata && \
    adduser -D tidepool
WORKDIR /app
COPY --from=development /go/src/github.com/tidepool-org/platform/_bin/services/data/ .
USER tidepool
ENTRYPOINT ["/app/data"]
